/* tslint:disable */
/* eslint-disable */
/**
 * sample-dotnet-webapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CsvUploadDetails
 */
export interface CsvUploadDetails {
    /**
     * 
     * @type {string}
     * @memberof CsvUploadDetails
     */
    objName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CsvUploadDetails
     */
    uploadLink?: string | null;
}

/**
 * Check if a given object implements the CsvUploadDetails interface.
 */
export function instanceOfCsvUploadDetails(value: object): value is CsvUploadDetails {
    return true;
}

export function CsvUploadDetailsFromJSON(json: any): CsvUploadDetails {
    return CsvUploadDetailsFromJSONTyped(json, false);
}

export function CsvUploadDetailsFromJSONTyped(json: any, ignoreDiscriminator: boolean): CsvUploadDetails {
    if (json == null) {
        return json;
    }
    return {
        
        'objName': json['objName'] == null ? undefined : json['objName'],
        'uploadLink': json['uploadLink'] == null ? undefined : json['uploadLink'],
    };
}

export function CsvUploadDetailsToJSON(json: any): CsvUploadDetails {
    return CsvUploadDetailsToJSONTyped(json, false);
}

export function CsvUploadDetailsToJSONTyped(value?: CsvUploadDetails | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objName': value['objName'],
        'uploadLink': value['uploadLink'],
    };
}

